### ISSUE TITLE
Replace `grit` with `rugged`

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/gridware#9]
_From @mjtko on May 13, 2016 15:45_

`grit` has been abandoned and doesn’t work correctly with Ruby 2.x without haxxx.

Investigate replacing `grit` with the suggested maintained library, `rugged`:

https://github.com/libgit2/rugged

_Copied from original issue: alces-software/clusterware#147_

**Comment by mjtko** [comment]
Fixed in https://github.com/alces-software/gridware/releases/tag/20180215
